### ISSUE TITLE
Uloskirjautumisongelma

### ISSUE THREAD

**Issue by TK009** [TK009/loyly#14]
Jos on kirjautunut, klikkaa galleriaan, sieltä jäsenet ja liittyminen sivulla ja sit koittaa kirjautua ulos niin ei toimi. -- @KatsCyl

**Comment by SimSaladin** [comment]
En saa tätä esiintymään itselläni chromiumilla enkä ff:llä, @TK009 @KatsCyl lisäinfoa?

**Comment by TK009** [comment]
en kyllä itsekkään, kopioin ongelman @KatsCyl viestistä irkistä.

**Comment by SimSaladin** [comment]
Epäilen @KatsCyl selaimen käyttäytymistä. Niin random ongelma et avaa uudestaan jos pystyy näyttämään konsistentisti.
